AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - com.amazon::LambdaQuarkus
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Api Gateway for Quarkus demo
      StageName: prod
  LambdaQuarkusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: s3://summer-entertainment/792e6cfc60379b8fe7cdd8c9459a65d9
      MemorySize: 256
      Timeout: 30
      Events:
        LambdaQuarkusUpdateSheet:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: /summerEntertainment/sheets/update
            Method: POST
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  ApiUrl:
    Description: URL of the users listing in the prod stage
    Value:
      Fn::Sub: https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod
